### ISSUE TITLE
Consider moving RabbitMQ subscriber in a separate project

### ISSUE THREAD

**Issue by SergeyKanzhelev** [fbeltrao/dotnet-observability-sample#4]
Perhaps it can even be directly moved to OpenTelemetry project. At least move it to a separate project so it will be guaranteed decoupled from the rest of an app logic

**Comment by fbeltrao** [comment]
For it to be a good target to OpenTelemetry it would require [RabbitMQ DotNet SDK](https://github.com/rabbitmq/rabbitmq-dotnet-client) to publish activities (which it does not).
